### PR TITLE
Increase font size of organisation name in contact details pattern.

### PR DESCRIPTION
**Pull request by Wynndow**
It was noticed that the font size of the organisation name in the
contact details pattern was 16pt, which is less than the rest of the
details. It looked weird. Now it's 19pt.

### CODE REVIEW

**Comment by pcraig3** [comment]
Apparently, @ralph-hawkins approved this.  

It doesn't quite solve the problem it's looking to solve, so I'm going to do a bit of extra cleanup before giving this a thumbs up.

**Comment by pcraig3** [comment]
Added another pull request in the buyer frontend that goes along with this one: https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/442

**Comment by Wynndow** [comment]
Does yours supersede this one? Or shall I keep this one around?

**Comment by pcraig3** [comment]
Keep it.  They work together.

**Comment by pcraig3** [comment]
Ralph has approved mine to go in, so let's get this in as well.
👍  👍  👍

**Pull request merged**
