### PR TITLE
Make phase-banner into real pattern that we might actually use.

### PR DESCRIPTION
**Pull request by pcraig3**
The [buyer](https://github.com/alphagov/digitalmarketplace-buyer-frontend/blob/master/app/templates/_phase_banner.html) and [supplier](https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/master/app/templates/_phase_banner.html) app are both using their own versions of the phase banner, which are nearly identical.

Talked with @tombye about this yesterday and he said that maybe the thing to do was make the phase into a variable.

Seems to me there's 3 ways forward.

1. Remove `beta-banner` pattern: we don't need it, just let the frontend apps do their thing.
2. Make `beta-banner` entirely static: both apps are just using the same markup and we don't anticipate a need to change either of them.
3. Make the `phase` into a variable: this way we have a pattern, even though for all [intensive porpoises](http://cdn.styleforum.net/7/7a/7a50d724_a-man-with-a-porpoise-25171-1260418770-21.jpeg), we don't really need the flexibility. 

I think we want **2** or **3**.  What do you think, @tombye?

### CODE REVIEW

**Comment by ralph-hawkins** [comment]
Don't forget the version on the homepage that has white on blue.

**Comment by pcraig3** [comment]
@ralph-hawkins I was thinking that would be better handled by the app itself, but maybe you're right that it would be better handled by the toolkit.

**Comment by ralph-hawkins** [comment]
Having all the styles in the same place sounds good to me

**Comment by pcraig3** [comment]
Sorry, @ralph-hawkins, but @tombye has vetoed the frontpage changes.  Keep the styles in the supplier app because the homepage is a special thing.  

:boom: :boom: :ralph: :boom: :boom:

**Comment by tombye** [comment]
I did, sorry Ralph. I just think the home page styles are specific to that cascade so it feels a bit strange viewing them out of that context.
At the least, this forms a good base for 99% of usage across the apps so it can be grown if needed (we can chat about it and see).

**Comment by tombye** [comment]
@pcraig3 it seems like renaming the macro file makes this a breaking change, shouldn't it be `18.0.0`?

**Comment by pcraig3** [comment]
ughhhh.

fiiiiiiine.

**Comment by tombye** [comment]
Once all conflicts are sorted 👍

**Pull request merged**
