### PR TITLE
Single field pricing question

### PR DESCRIPTION
**Pull request by Wynndow**
If the case is that a pricing question only has one field, we should
render a simpler label.

Also, there's no need to use pricing columns and the more complicated
code that comes with it. We use the simple text box format instead.

### CODE REVIEW

**Comment by pcraig3** [comment]
🙀

**Comment by Wynndow** [comment]
@pcraig3 Lunatic

**Comment by tombye** [comment]
At some point we need to make it so the top pattern is just an import of the `forms/textbox.html` macro. I mean so any changes to the textbox this code is copied from update automatically.
Doing this now would mean changing the import path used across the apps so for now, this is 👍

**Comment by Wynndow** [comment]
@tombye Hey Tom, we spotted something after you gave this a thumbs up. Could you take a look at that last commit for us?

**Comment by tombye** [comment]
Good spot. Now needs a rebase + the version bump changed to be to the new version but once that's done: 👍

**Pull request merged**
