### PR TITLE
Make JavaScript tests run in CI

### PR DESCRIPTION
**Pull request by tombye**
Uses the same testrunner as in other apps.

### CODE REVIEW

**Comment by quis** [comment]
I think you need to add a `travis.yml` like [the one in the supplier app](https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/master/.travis.yml) to actually get the tests to run.

**Comment by allait** [comment]
I've made a change in Travis CI to enable running tests on this repo, but I think it needs a git push to trigger it for the first time

**Comment by quis** [comment]
Pushed an empty commit to this branch, tests are running here: https://travis-ci.org/alphagov/digitalmarketplace-frontend-toolkit/builds/81363696

…and they've passed, but haven't run any of the tests.

Going to reset this branch to before I meddled now.

**Comment by allait** [comment]
Travis shows a "This job ran on our legacy infrastructure" warning on these builds, even though recently created projects should default to the container builds. I think we should add `sudo: false` to `.travis.yml` to fix this

**Comment by tombye** [comment]
OK, so the problem was the specs were listed in `spec/javascripts/manifest.js` with a lowercase letter to start but the files started with an uppercase letter. 

Looks like this was working on our Macs because our hard drives are formatted to have case-insensitive file handling.

**Comment by quis** [comment]
Good sleuthing :+1:

**Pull request merged**
