### PR TITLE
Lb tweak search results summary

### PR DESCRIPTION
**Pull request by laurenceberry**
Related PR: https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/680

Originally I planned to just add a border to the summary results for the opportunities page but then realised that the search results summary needed more consideration.

This commit:
• adds a border to the bottom of all search summaries on search results pages
• removes a border-top from the save search
• increases the font-size for search results summary and suggestion
• increases font sizes for mobile

Before:
screen shot 2017-12-11 at 12 13 10

screen shot 2017-12-11 at 12 12 36

screen shot 2017-12-11 at 12 15 47

After:

screen shot 2017-12-11 at 11 59 46

screen shot 2017-12-11 at 12 00 03

screen shot 2017-12-11 at 11 28 29

### CODE REVIEW

**Comment by DilwoarH** [comment]
Is 16 big enough?

Maybe something a bit larger to give it some sort of presence.

16:
screen shot 2017-12-11 at 15 48 02

23:
screen shot 2017-12-11 at 15 47 56

**Comment by TheDoubleK** [comment]
I suspect at least some of our users have come to know and love the **massive** numbering. Certainly I remember labs in the past where G-Cloud buyers have talked about their main objective when searching being to get this number low enough. But having things all the same size does look neater. I'd agree with Dilwoar that it should probably be more prominent on the page though - the headline number is definitely the main focus for at least some of our users.

Would be nice for the commit message to have a bit more detail of what has changed here maybe ("improve" is a very subjective term!).

**Comment by samuelhwilliams** [comment]
Is there any user research saying that we _should_ make the number smaller, or is this coming primarily from a design standpoint? I quite like the large numbers and it feels like it does help users quickly grok how close they are to their goal of reaching a reasonable shortlist.

**Comment by laurenceberry** [comment]
To be fair, I think I got carried away. Changing the size of the summary results wasn't really what this was about. Originally I was simply trying to add a border top for DOS results and went down a bit of a rabbit hole. Its probably best to either delete this PR.

**Comment by samuelhwilliams** [comment]
Happy to close this then @laurenceberry?

**Comment by samuelhwilliams** [comment]
Seems like we can close this.

**Pull request closed without merging**
